name: Docker Image CI

on:
  push:
    branches: 
      - master
  schedule:
    # Weekly on Sundays at 02:00
    - cron: '0 2 * * 0'
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: quintesse/vertx-configmap-example/vertx-configmap-example
        username: quintesse
        password: ${{ secrets.GITHUB_TOKEN }}
        snapshot: true
        # Cache everything except scheduled builds
        cache: github.event_name != 'schedule'
